"""Ajout du Leasing dans Application

Revision ID: e9bbd9237142
Revises: 
Create Date: 2026-05-21 21:30:10.314392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bbd9237142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_achat_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('valeur_residuelle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('option_achat_levee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_levee_option', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('date_levee_option')
        batch_op.drop_column('option_achat_levee')
        batch_op.drop_column('valeur_residuelle')
        batch_op.drop_column('option_achat_active')

    # ### end Alembic commands ###
